import {
  Wallet,
  Home,
  ShoppingCart,
  Shield,
  GraduationCap,
  Users,
  TrendingUp,
  Send,
  ArrowDownLeft,
  Plus,
  Lock,
  Unlock,
  Clock,
  BarChart3,
  User,
  Settings,
  ChevronRight,
  ArrowUpRight,
  ArrowDownRight,
  Search,
  Bell,
  Menu,
} from "lucide-react"

export const Icons = {
  wallet: Wallet,
  home: Home,
  shoppingCart: ShoppingCart,
  shield: Shield,
  graduationCap: GraduationCap,
  users: Users,
  trendingUp: TrendingUp,
  send: Send,
  receive: ArrowDownLeft,
  plus: Plus,
  lock: Lock,
  unlock: Unlock,
  clock: Clock,
  chart: BarChart3,
  user: User,
  settings: Settings,
  chevronRight: ChevronRight,
  arrowUp: ArrowUpRight,
  arrowDown: ArrowDownRight,
  search: Search,
  bell: Bell,
  menu: Menu,
}

export type IconName = keyof typeof Icons
