-- Create 3 Budget Wallets with maximized settings for user ea18995b-d3b0-41a5-a57c-d55b608fbe58

-- Budget Wallet 1: Monthly Entertainment Budget
INSERT INTO budget_wallets (
  id,
  user_id,
  name,
  purpose,
  balance,
  spend_limit,
  is_locked,
  lock_until,
  disbursement_frequency,
  day_of_week,
  enable_rollover,
  automatic_allocation,
  allocation_frequency,
  allocation_day,
  auto_allocation_amount,
  custom_notifications,
  currency,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'ea18995b-d3b0-41a5-a57c-d55b608fbe58',
  'Entertainment & Fun',
  'Monthly budget for movies, concerts, dining out, and entertainment activities',
  50000.00,
  50000.00,
  false,
  NULL,
  'monthly',
  'friday',
  true,
  true,
  'weekly',
  5,
  12500.00,
  true,
  'NGN',
  NOW(),
  NOW()
);

-- Budget Wallet 2: Groceries & Essentials (Locked)
INSERT INTO budget_wallets (
  id,
  user_id,
  name,
  purpose,
  balance,
  spend_limit,
  is_locked,
  lock_until,
  disbursement_frequency,
  day_of_week,
  enable_rollover,
  automatic_allocation,
  allocation_frequency,
  allocation_day,
  auto_allocation_amount,
  custom_notifications,
  currency,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'ea18995b-d3b0-41a5-a57c-d55b608fbe58',
  'Groceries & Household',
  'Weekly grocery shopping and household essentials budget - locked to prevent overspending',
  75000.00,
  100000.00,
  true,
  NOW() + INTERVAL '30 days',
  'weekly',
  'monday',
  false,
  true,
  'bi-weekly',
  15,
  25000.00,
  true,
  'NGN',
  NOW(),
  NOW()
);

-- Budget Wallet 3: Transportation & Fuel
INSERT INTO budget_wallets (
  id,
  user_id,
  name,
  purpose,
  balance,
  spend_limit,
  is_locked,
  lock_until,
  disbursement_frequency,
  day_of_week,
  enable_rollover,
  automatic_allocation,
  allocation_frequency,
  allocation_day,
  auto_allocation_amount,
  custom_notifications,
  currency,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'ea18995b-d3b0-41a5-a57c-d55b608fbe58',
  'Transport & Fuel',
  'Monthly transportation costs including fuel, parking, and ride-sharing services',
  40000.00,
  60000.00,
  false,
  NULL,
  'bi-weekly',
  'wednesday',
  true,
  true,
  'monthly',
  1,
  20000.00,
  true,
  'NGN',
  NOW(),
  NOW()
);

-- Create 5 Goal Wallets with maximized settings

-- Goal Wallet 1: New Car Fund
INSERT INTO goal_wallets (
  id,
  user_id,
  name,
  purpose,
  balance,
  target_amount,
  target_date,
  progress_percentage,
  auto_schedule_amount,
  auto_schedule_frequency,
  flex_contributions,
  smart_reminders,
  funding_source,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'ea18995b-d3b0-41a5-a57c-d55b608fbe58',
  'New Car Purchase',
  'Saving for a brand new Toyota Camry 2025 model with full features',
  2500000.00,
  8000000.00,
  '2026-12-31',
  31.25,
  150000.00,
  'weekly',
  true,
  true,
  'auto-schedule',
  NOW(),
  NOW()
);

-- Goal Wallet 2: Vacation to Dubai
INSERT INTO goal_wallets (
  id,
  user_id,
  name,
  purpose,
  balance,
  target_amount,
  target_date,
  progress_percentage,
  auto_schedule_amount,
  auto_schedule_frequency,
  flex_contributions,
  smart_reminders,
  funding_source,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'ea18995b-d3b0-41a5-a57c-d55b608fbe58',
  'Dubai Vacation 2025',
  'Family vacation to Dubai including flights, 5-star hotel, and activities',
  850000.00,
  3000000.00,
  '2025-08-15',
  28.33,
  100000.00,
  'bi-weekly',
  true,
  true,
  'auto-schedule',
  NOW(),
  NOW()
);

-- Goal Wallet 3: Emergency Fund
INSERT INTO goal_wallets (
  id,
  user_id,
  name,
  purpose,
  balance,
  target_amount,
  target_date,
  progress_percentage,
  auto_schedule_amount,
  auto_schedule_frequency,
  flex_contributions,
  smart_reminders,
  funding_source,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'ea18995b-d3b0-41a5-a57c-d55b608fbe58',
  'Emergency Fund',
  'Building a 6-month emergency fund for unexpected expenses and financial security',
  1800000.00,
  5000000.00,
  '2026-06-30',
  36.00,
  200000.00,
  'monthly',
  true,
  true,
  'auto-schedule',
  NOW(),
  NOW()
);

-- Goal Wallet 4: Home Renovation
INSERT INTO goal_wallets (
  id,
  user_id,
  name,
  purpose,
  balance,
  target_amount,
  target_date,
  progress_percentage,
  auto_schedule_amount,
  auto_schedule_frequency,
  flex_contributions,
  smart_reminders,
  funding_source,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'ea18995b-d3b0-41a5-a57c-d55b608fbe58',
  'House Renovation Project',
  'Complete home renovation including kitchen upgrade, new flooring, and bathroom remodel',
  3200000.00,
  10000000.00,
  '2027-03-31',
  32.00,
  250000.00,
  'weekly',
  true,
  true,
  'auto-schedule',
  NOW(),
  NOW()
);

-- Goal Wallet 5: MacBook Pro Purchase
INSERT INTO goal_wallets (
  id,
  user_id,
  name,
  purpose,
  balance,
  target_amount,
  target_date,
  progress_percentage,
  auto_schedule_amount,
  auto_schedule_frequency,
  flex_contributions,
  smart_reminders,
  funding_source,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'ea18995b-d3b0-41a5-a57c-d55b608fbe58',
  'MacBook Pro M4',
  'Saving for the latest MacBook Pro M4 with 32GB RAM for professional work',
  450000.00,
  1500000.00,
  '2025-06-30',
  30.00,
  75000.00,
  'bi-weekly',
  true,
  true,
  'auto-schedule',
  NOW(),
  NOW()
);
